# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false
kotlin.code.style=official

org.gradle.parallel=false
android.useAndroidX=true
android.enableJetifier=true

# AGGRESSIVE SIZE OPTIMIZATION
android.enableR8.fullMode=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=true

# COMPATIBILITY FIXES
android.builtInKotlin=false
android.newDsl=false
